### ISSUE TITLE
请问是否能够开放训练数据的下载？

### ISSUE THREAD

**Issue by zhoujz10** [baidu/lac#10]
如题，非常感谢！

**Comment by sdshq** [comment]
训练数据样例可以在项目中找到。完整的训练数据非常大，我们后续会讨论是否能够以某种合适的方式开放一部分。

**Comment by xxllp** [comment]
good ，自己训练的话有没有啥注意点

**Comment by TankAbraham** [comment]
@sdshq 您好，是否有在超大型语料上已经训练好的模型，可以供我们直接调用呢？

**Comment by TankAbraham** [comment]
@sdshq 就像 Google 开放了 BERT模型参数那样的预训练好的模型，可以让使用者直接调用的？

**Comment by sdshq** [comment]
发布的模型是在大规模的语料上训练过的。Bert我们在线下调研有较大收益，我们尽快排期更新。

**Comment by TankAbraham** [comment]
@sdshq 谢谢！
“发布的模型是在大规模的语料上训练过的”，意思是说，我们调用时使用默认的模型，就可以享用在大规模语料上训练过的模型了吗？
您应该是这个意思吧？！ ^_^
