### ISSUE TITLE
能否实现全分词？

### ISSUE THREAD

**Issue by 0x376h** [baidu/lac#101]
lac能把per和org整体切出，但有些场景可能需要全分词。
如北京市百度有限公司 能否切出
北京市 百度 有限公司？

**Comment by Bond-H** [comment]
这个可以在人民日报数据或北大分词数据上进行增量训练，得到一个更细粒度的分词结果

**Comment by zhouzusheng** [comment]
能提供你训练好的 pku_lacmodel 吗

**Comment by Bond-H** [comment]
链接:https://pan.baidu.com/s/1oPFNpQ_q9pkTxpCw5icCzg  密码:8doi

可以从http://sighan.cs.uchicago.edu/bakeoff2005/ 下载数据，直接调用增量训练接口即可，以上模型是只使用其中pku_training.utf8训练所得模型，一般作为应用的时候，使用训练集+测试集进行模型训练，也可以使用更大的训练数据集，如人民日报2014年的数据集

**Comment by 0x376h** [comment]
了解，因为不是基于完全的字典的，所以针对全分词的场景只能重新训练一个模型？

**Comment by Bond-H** [comment]
@0x376h 嗯嗯，对于不同粒度需求的都要进行粒度迁移，我们提供的训练接口是增量的训练，复用过去的参数，具有较强的泛化能力

**Comment by jieli4970** [comment]
@Bond-H 咨询下，在增量训练时对单条文本长度有限制吗？我看args.ini里面未提及seq len。另外增量训练的batch取得是args.ini这个配置文件里面的参数么。谢谢大佬回复
