### ISSUE TITLE
LAC初始化输出异常日志

### ISSUE THREAD

**Issue by icecream0** [baidu/lac#103]
W0717 19:29:42.811772 29240 analysis_predictor.cc:518]  - GLOG's LOG(INFO) is disabled.
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [attention_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [seqconv_eltadd_relu_fuse_pass]e[0m
e[32m--- Running IR pass [seqpool_cvm_concat_fuse_pass]e[0m
e[32m--- Running IR pass [fc_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [mul_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [fc_gru_fuse_pass]e[0m
这些日志表示什么呢，是否可以设置不要日志输出

**Comment by Bond-H** [comment]
这些信息是对网络op的优化，升级paddlepaddle至1.8以上版本会默认关闭，你这个应该还是用的旧版的paddle
