### ISSUE TITLE
加载自定义词典性能问题

### ISSUE THREAD

**Issue by luozhouyang** [baidu/lac#105]
加载词典非常慢。

以结巴[dict.txt.big](https://github.com/fxsjy/jieba/blob/master/extra_dict/dict.txt.big)为例，需要好几分钟才能完成加载。

**Comment by luozhouyang** [comment]
有人关注这个问题嘛？可以复现的链接 [lac_load_custom_dict](https://colab.research.google.com/drive/1WBSUXruAVsNH3SNZp8s5SsNRRMJlqk0u?usp=sharing)

**Comment by Mangomomo** [comment]
同样表示关注，我也想自定义词典配置，准备尝试一下~

**Comment by Mangomomo** [comment]
刚看了，你下载的jieba的dict.txt.big的格式内容和lac 示例的custom.txt的格式好像不一致呢

**Comment by luozhouyang** [comment]
把jieba的词典中频次和词性去除，加载还是很慢。

**Comment by moberq** [comment]
> 加载词典非常慢。
> 
> 以结巴[dict.txt.big](https://github.com/fxsjy/jieba/blob/master/extra_dict/dict.txt.big)为例，需要好几分钟才能完成加载。

词典加载慢的问题已在版本2.0.5中修复
详情见：https://pypi.org/project/LAC/2.0.5/

**Comment by moberq** [comment]
> 同样表示关注，我也想自定义词典配置，准备尝试一下~

词典加载慢的问题已在版本2.0.5中修复
详情见：https://pypi.org/project/LAC/2.0.5/

**Comment by luozhouyang** [comment]
感谢各位大佬！经验证，加载jieba.big.txt词典，时间下降到5s左右。
