### ISSUE TITLE
java批量运行时报错，并发20

### ISSUE THREAD

**Issue by elninom** [baidu/lac#109]
![image](https://user-images.githubusercontent.com/39551225/88356169-839cc080-cd99-11ea-9de6-09b05d4d88b6.png)

**Comment by elninom** [comment]
具体代码是这样 
![image](https://user-images.githubusercontent.com/39551225/88356923-0f175100-cd9c-11ea-91e8-c80af9bb7ab6.png)
![image](https://user-images.githubusercontent.com/39551225/88356970-2b1af280-cd9c-11ea-8bc4-9fb3585ef4c3.png)

**Comment by Bond-H** [comment]
Java的相关代码已经升级，该问题应该已经解决了，多线程调用可参考示例 LacMulti.java

**Comment by elninom** [comment]
> Java的相关代码已更新多线程调用相关内容，该问题应该已经解决了，多线程调用可参考示例 LacMulti.java

你好，问一下第一张图的报错信息是什么，现在发现好像不是由于并发引起的，是不是因为句子的问题而引起的

**Comment by moberq** [comment]
> > Java的相关代码已更新多线程调用相关内容，该问题应该已经解决了，多线程调用可参考示例 LacMulti.java
> 
> 你好，问一下第一张图的报错信息是什么，现在发现好像不是由于并发引起的，是不是因为句子的问题而引起的

从日志信息来看，是内存不足导致的错误。

建议结合机器本身的配置，综合考虑query的长度和batch_size的大小，跑之前先预估一下相应的阈值。
