### ISSUE TITLE
关于ｄｏｃｋｅｒ

### ISSUE THREAD

**Issue by yuppx** [baidu/lac#11]
我本身使用的是Ｕｂｕｎｔｕ１６．４，不打算使用ｄｏｃｋｅｒ，可以直接跳过安装步骤的第二步，以及第三步的第一行命令（ｄｏｃｋｅｒ run -it -v $pwd:/paddle -w /paddle paddle:dev /bin/bash） ，直接建立ｂｕｉｌｄ　文件夹吗？

**Comment by wanbiguizhao** [comment]
我用的是docker，docker知识提供了一下gcc，cmake等编译环境，如果本地安装相关软件，那么不用docker应该没有问题。

**Comment by yuppx** [comment]
我直接运行命令python python/train.py 时，出现了以下错误：
Traceback (most recent call last):
  File "python/train.py", line 304, in <module>
    train(args)
  File "python/train.py", line 191, in train
    word_dict_len = max(map(int, word2id_dict.values())) + 1                
ValueError: max() arg is an empty sequence

此外，请问运行ｌａｃ一定要在ｄｏｃｋｅｒ容器内吗？　如果不用ｄｏｃｋｅｒ环境怎么加载ｐａｄｄｌｅ模块来运行ｌａｃ？

**Comment by iceman1212** [comment]
因为 项目中使用了LFS(Large File Storage, 大文件存储)，conf文件夹内的文件内容没有下载下来。
你点击下面链接，每一个文件 单独下载 放到项目的conf内
>https://github.com/baidu/lac/tree/master/conf

**Comment by wanbiguizhao** [comment]
安装好 lfs之后，在项目的目录下：执行git install gls，git gls pull 可以获得文件。

**Comment by yuppx** [comment]
这个获得文件的步骤能再详细些吗

**Comment by yuppx** [comment]
请问训练时的迭代次数如何设置？
