### ISSUE TITLE
深度操作系统 java 1.8 调用 LacDemo报错

### ISSUE THREAD

**Issue by gs80140** [baidu/lac#110]
感谢百度lac团队开源 lac 给大家使用

根据 https://github.com/baidu/lac/tree/master/java 例子，在深度操作系统下， 编译 so文件成功

预测库下载的 https://paddle-inference-lib.bj.bcebos.com/1.8.3-cpu-avx-mkl/fluid_inference.tgz
这里怀疑可能是版本不兼容导致的，后面准备自己生成

模型是下载的 https://github.com/baidu/lac/releases/download/v2.0.0/models_general.zip

贴出来我的编译过程
cd lac
PADDLE_ROOT=/tools/fluid_inference
JAVA_HOME=/tools/jdk1.8.0_261
mkdir build 
cd build
cmake -DPADDLE_ROOT=$PADDLE_ROOT \
      -DJAVA_HOME=$JAVA_HOME \
      -DWITH_JNILIB=ON \
      -DWITH_DEMO=OFF \
      ../
make install

然后在 output目录产生了demo代码及 liblacjni.so

看到了其它 issue是报找不到lib，我没有遇到 ，我直接把这个 so文件放在了 /usr/lib 目录下面的，可以直接加载 
但是运行 demo时报错

demo命令
java LacDemo /data/lac/models_general

报错
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ffa65bcc6cb, pid=28494, tid=0x00007ffa8a493700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_261-b12) (build 1.8.0_261-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.261-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [liblacjni.so+0xf6c6cb]  paddle::AnalysisConfig::SerializeInfoCache()+0x1fb
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /codes/lac/output/java/hs_err_pid28494.log
错误文件已上传
[hs_err_pid28494.log](https://github.com/baidu/lac/files/4985784/hs_err_pid28494.log)

#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
已放弃
```

现在初步估计就是 预测库 是下载而不是编译的， 准备自己编译 一下试试

**Comment by Bond-H** [comment]
嗯嗯，从报错信息上看，确实是在调用预测库时出错了

**Comment by gs80140** [comment]
paddle 预编译 
git clone https://github.com/PaddlePaddle/Paddle.git
cd Paddle
git checkout v1.8.3
mkdir build
cd build
mkdir -p /data/paddle
PADDLE_ROOT=/data/paddle
cmake -DFLUID_INFERENCE_INSTALL_DIR=$PADDLE_ROOT \
      -DCMAKE_BUILD_TYPE=Release \
      -DWITH_PYTHON=OFF \
      -DWITH_MKL=OFF \
      -DWITH_GPU=OFF  \
      -DON_INFER=ON \
      ../
make
make inference_lib_dist


然后调用 java LacDemo /home/jinna/tools/models_general/lac_model 报错

Please compile with MKLDNN first to use MKLDNN

正在学习如何带上 MKLDNN 编译

**Comment by gs80140** [comment]
带上编译参数后，可以正常使用，已经正常用上了。感谢百度lac团队。

**Comment by changingshow** [comment]
> 带上编译参数后，可以正常使用，已经正常用上了。感谢百度lac团队。

我也遇到了同样的问题，您是怎么解决的，带了什么编译参数？是把DWITH_MKL=OFF 改成ON吗？

**Comment by changingshow** [comment]
> > 带上编译参数后，可以正常使用，已经正常用上了。感谢百度lac团队。
> 
> 我也遇到了同样的问题，您是怎么解决的，带了什么编译参数？是把DWITH_MKL=OFF 改成ON吗？

自问自答。是的。
