### ISSUE TITLE
关于支持依存句法分析

### ISSUE THREAD

**Issue by HeroadZ** [baidu/lac#112]
感谢开源！
想请教一下是否有考虑加入依存句法分析？
或者有推荐的工具吗？

**Comment by Bond-H** [comment]
百度近期已开源依存句法分析工具DDParser：https://github.com/baidu/DDParser
欢迎试用体验

**Comment by HeroadZ** [comment]
@Bond-H 感谢！顺便想问一下，DDParser和哈工大的LTP哪个准确度更高一点呢？

**Comment by Bond-H** [comment]
DDParser 应该有更强的通用能力，具体效果可自行使用不同语料进行测试
