### ISSUE TITLE
关于编译LAC的问题

### ISSUE THREAD

**Issue by Dyleaf** [baidu/lac#12]
问题描述：
原文中编译LAC操作：
```
cd build
# /path/to/fluid_inference_lib是上节第五步的对应的Fluid预测库编译产出路径
# LAC的demo程序，以及依赖LAC静态库的程序，都要依赖这个路径作为动态库的搜索路径
# 如果这个路径在编译完成之后有变动，需要手工设置LD_LIBRARY_PATH环境变量
cmake -DPADDLE_ROOT=/path/to/fluid_inference_lib ..
make
make install # 编译产出在 ../output 下
```

问题： 我的操作没有output文件夹生成，我的操作过程是
```
cd bulid
cmake -DPADDLE_ROOT=../bulid/fluid_install_dir/ ..
```
后面在bulid内没有新生成的文件。
于是在当前目录以及上一级执行了make 以及make install 后通过 find 命令查找，发现没有output文件夹生成。

关于这一步的操作能否详细说明下，非常感谢。

**Comment by wanbiguizhao** [comment]
首先你要下载Paddle，在paddle对应的代码中，执行编译Fluid操作，确保Fluid编译成功。
我编译Fluid 生成了编译目录为：Paddle/build/fluid_install_dir    我设置的是：DPADDLE_ROOT = /前缀路径Paddle/build/fluid_install_dir
编译成功，可以看到output文件夹了。

**Comment by yuppx** [comment]
我的操作是：cmake -DPADDLE_ROOT=/home/chase/yq/Paddle/build/fluid_install_dir
出现了这样的错误
CMake Error: The source directory "/home/chase/yq/Paddle/lac/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
为什么会这样？
