### ISSUE TITLE
能够提供Python预测的示例代码？

### ISSUE THREAD

**Issue by wanbiguizhao** [baidu/lac#13]
训练是使用Python做的，能否提供基于Python的预测示例代码？或者给出相应的教程。

**Comment by sunhf** [comment]
可以，我们近期会把项目的python预测代码上传一下。
暂时也可以参考 https://github.com/PaddlePaddle/models/blob/develop/fluid/chinese_ner/infer.py 这个预测代码的实现，输入部分需要作下改动。

**Comment by wanbiguizhao** [comment]
非常感谢

**Comment by jshower** [comment]
在python目录下，已经添加infer.py作为示例代码，欢迎试用。
