### ISSUE TITLE
无法加载paddle模块

### ISSUE THREAD

**Issue by yuppx** [baidu/lac#14]
我在运行python python/train.py -h命令时，出现以下错误：
Traceback (most recent call last):
  File "python/train.py", line 12, in <module>
    import paddle
ImportError: No module named paddle

请问怎么解决

**Comment by iceman1212** [comment]
没有安装Paddle
[https://github.com/baidu/lac/blob/master/README.md#%E5%AE%89%E8%A3%85paddle](url)

**Comment by yuppx** [comment]
我是按照步骤进行的啊，会是镜像安装错了吗？

**Comment by wanbiguizhao** [comment]
执行下docker images 看下镜像看看？

**Comment by yuppx** [comment]
chase@chase-pc:~$ sudo docker images
REPOSITORY                          TAG                            IMAGE ID            CREATED             SIZE
paddle                              dev                            023a36458384        13 hours ago        5.29GB

**Comment by yuppx** [comment]
问一个比较幼稚的问题哈，我用的Ｕｂｕｎｔｕ１６．０４.科学上网一直是个大问题！！！　请问有没有什么建设性方法？能够使Ｕｂｕｎｔｕ　全局代理

**Comment by wanbiguizhao** [comment]
REPOSITORY                          TAG                 IMAGE ID            CREATED             SIZE
docker.paddlepaddlehub.com/paddle   latest              81b6a542a719        7 days ago          1.46GB
paddlepaddle/book                   latest              d53ae65f855e        12 days ago         2.48GB

**Comment by wanbiguizhao** [comment]
咱两个好像docker镜像不一样。

**Comment by wanbiguizhao** [comment]
https://blog.csdn.net/hanshileiai/article/details/52624303  这个是我科学上网通过wrt走的

**Comment by yuppx** [comment]
我也设置了，通过wget是可以下载文件的，但在构建镜像时文件依旧有下载出错．可以的话可以加一下联系方式吗．Ｑ１４７５２２１４９２

**Comment by wanbiguizhao** [comment]
抱歉，问题解决了吗？ 
我当初是执行的这个命令
docker build -t paddle:dev --build-arg UBUNTU_MIRROR='http://mirrors.ustc.edu.cn/ubuntu/' .
