### ISSUE TITLE
Invalid CPU memory access

### ISSUE THREAD

**Issue by JackieTien97** [baidu/lac#145]
当传入数组过大时，会报错
![image](https://user-images.githubusercontent.com/16079446/97958754-d3ebdb80-1de8-11eb-88ad-3deef21a56cd.png)

**Comment by Bond-H** [comment]
模型确实会随着输入size分配内存，如果数组过大，确实会存在内存不足的情况，这需要用户自行对数组进行拆分，或者以单个句子进行输入
