### ISSUE TITLE
直接使用GitHub源码调用报错 Expected desc->check_guards() == true, but received desc->check_guards():0 != true:1

### ISSUE THREAD

**Issue by TestNLP** [baidu/lac#148]
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [attention_lstm_fuse_pass]
--- Running IR pass [seqconv_eltadd_relu_fuse_pass]
--- Running IR pass [seqpool_cvm_concat_fuse_pass]
--- Running IR pass [fc_lstm_fuse_pass]
--- Running IR pass [mul_lstm_fuse_pass]
--- Running IR pass [fc_gru_fuse_pass]
--- Running IR pass [mul_gru_fuse_pass]
--- Running IR pass [seq_concat_fc_fuse_pass]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [repeated_fc_relu_fuse_pass]
--- Running IR pass [squared_mat_sub_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [is_test_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [ir_graph_to_program_pass]
######### run:list ##############
Traceback (most recent call last):
  File "lac/lac.py", line 234, in <module>
    result = lac.run(test_data)
  File "lac/lac.py", line 89, in run
    crf_decode = self.predictor.run([tensor_words])
paddle.fluid.core_noavx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > paddle::platform::GetTraceBackString<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*, int)
1   paddle::memory::detail::MetadataCache::load(paddle::memory::detail::MemoryBlock const*) const
2   paddle::memory::detail::MemoryBlock::split(paddle::memory::detail::MetadataCache*, unsigned long)
3   paddle::memory::detail::BuddyAllocator::SplitToAlloc(std::__1::__tree_const_iterator<std::__1::tuple<unsigned long, unsigned long, void*>, std::__1::__tree_node<std::__1::tuple<unsigned long, unsigned long, void*>, void*>*, long>, unsigned long)
4   paddle::memory::detail::BuddyAllocator::Alloc(unsigned long)
5   void* paddle::memory::legacy::Alloc<paddle::platform::CPUPlace>(paddle::platform::CPUPlace const&, unsigned long)
6   paddle::memory::allocation::NaiveBestFitAllocator::AllocateImpl(unsigned long)
7   paddle::memory::allocation::Allocator::Allocate(unsigned long)
8   paddle::memory::allocation::AllocatorFacade::AllocShared(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, unsigned long)
9   paddle::memory::AllocShared(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, unsigned long)
10  paddle::framework::Tensor::mutable_data(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, paddle::framework::proto::VarType_Type, unsigned long)
11  float* paddle::framework::Tensor::mutable_data<float>(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, unsigned long)
12  paddle::operators::FusionGRUKernel<float>::SeqCompute(paddle::framework::ExecutionContext const&) const
13  paddle::operators::FusionGRUKernel<float>::Compute(paddle::framework::ExecutionContext const&) const
14  std::__1::__function::__func<paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::FusionGRUKernel<float>, paddle::operators::FusionGRUKernel<double> >::operator()(char const*, char const*, int) const::'lambda'(paddle::framework::ExecutionContext const&), std::__1::allocator<paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::FusionGRUKernel<float>, paddle::operators::FusionGRUKernel<double> >::operator()(char const*, char const*, int) const::'lambda'(paddle::framework::ExecutionContext const&)>, void (paddle::framework::ExecutionContext const&)>::operator()(paddle::framework::ExecutionContext const&)
15  paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const
16  paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const
17  paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&)
18  paddle::framework::NaiveExecutor::Run()
19  paddle::AnalysisPredictor::Run(std::__1::vector<paddle::PaddleTensor, std::__1::allocator<paddle::PaddleTensor> > const&, std::__1::vector<paddle::PaddleTensor, std::__1::allocator<paddle::PaddleTensor> >*, int)
20  void pybind11::cpp_function::initialize<paddle::pybind::(anonymous namespace)::BindAnalysisPredictor(pybind11::module*)::$_11, std::__1::vector<paddle::PaddleTensor, std::__1::allocator<paddle::PaddleTensor> >, paddle::AnalysisPredictor&, std::__1::vector<paddle::PaddleTensor, std::__1::allocator<paddle::PaddleTensor> > const&, pybind11::name, pybind11::is_method, pybind11::sibling>(paddle::pybind::(anonymous namespace)::BindAnalysisPredictor(pybind11::module*)::$_11&&, std::__1::vector<paddle::PaddleTensor, std::__1::allocator<paddle::PaddleTensor> > (*)(paddle::AnalysisPredictor&, std::__1::vector<paddle::PaddleTensor, std::__1::allocator<paddle::PaddleTensor> > const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::__invoke(pybind11::detail::function_call&)
21  pybind11::cpp_function::dispatcher(_object*, _object*, _object*)

----------------------
Error Message Summary:
----------------------
PaddleCheckError: Expected desc->check_guards() == true, but received desc->check_guards():0 != true:1.
 at [/Users/paddle/liujinquan/Paddle/paddle/fluid/memory/detail/meta_cache.cc:33]

libc++abi.dylib: terminating with uncaught exception of type paddle::platform::EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > paddle::platform::GetTraceBackString<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*, int)
1   paddle::memory::detail::MetadataCache::load(paddle::memory::detail::MemoryBlock const*) const
2   paddle::memory::detail::MemoryBlock::type(paddle::memory::detail::MetadataCache const&) const
3   paddle::memory::detail::BuddyAllocator::Free(void*)
4   void paddle::memory::legacy::Free<paddle::platform::CPUPlace>(paddle::platform::CPUPlace const&, void*, unsigned long)
5   paddle::memory::allocation::NaiveBestFitAllocator::FreeImpl(paddle::memory::allocation::Allocation*)
6   std::__1::__shared_ptr_pointer<paddle::memory::allocation::Allocation*, paddle::memory::allocation::Allocator::AllocationDeleter, std::__1::allocator<paddle::memory::allocation::Allocation> >::__on_zero_shared()
7   paddle::framework::Variable::PlaceholderImpl<paddle::framework::LoDTensor>::~PlaceholderImpl()
8   paddle::framework::Scope::~Scope()
9   paddle::framework::Scope::DeleteScope(paddle::framework::Scope*) const
10  paddle::AnalysisPredictor::~AnalysisPredictor()
11  paddle::AnalysisPredictor::~AnalysisPredictor()
12  pybind11::class_<paddle::AnalysisPredictor, paddle::PaddlePredictor>::dealloc(pybind11::detail::value_and_holder&)
13  pybind11::detail::clear_instance(_object*)
14  pybind11_object_dealloc

----------------------
Error Message Summary:
----------------------
PaddleCheckError: Expected desc->check_guards() == true, but received desc->check_guards():0 != true:1.
 at [/Users/paddle/liujinquan/Paddle/paddle/fluid/memory/detail/meta_cache.cc:33]

W1127 15:21:26.277645 389684672 init.cc:205] *** Aborted at 1606461686 (unix time) try "date -d @1606461686" if you are using GNU date ***
W1127 15:21:26.277863 389684672 init.cc:205] PC: @                0x0 (unknown)
W1127 15:21:26.278908 389684672 init.cc:205] *** SIGABRT (@0x7fff7021233a) received by PID 42885 (TID 0x1173a1dc0) stack trace: ***
W1127 15:21:26.279036 389684672 init.cc:205]     @     0x7fff702c35fd _sigtramp

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

**Comment by Bond-H** [comment]
系统版本、Python版本、LAC版本、paddle版本分别是什么呢？

**Comment by TestNLP** [comment]
> 系统版本、Python版本、LAC版本、paddle版本分别是什么呢？

系统是：mac 10.15.6 (19G2021)  LAC版本：2.0.5    paddle版本:paddlepaddle-tiny    1.6.1
我在linux系统上也出现同样错误，linux系统版本是：Linux version 4.19.0-0.bpo.9-amd64 (debian-kernel@lists.debian.org)，其他版本同上

**Comment by TestNLP** [comment]
@Bond-H

**Comment by Bond-H** [comment]
应该是输入中存在空字符串，导致模型运行失败，这个BUG在后续的paddle版本中已修复，推荐使用paddlepaddle-1.8.5

**Comment by TestNLP** [comment]
@Bond-H ，是安装paddlepaddle-tiny还是paddlepaddle？？这两个有区别吗？

**Comment by Bond-H** [comment]
推荐使用paddlepaddle，paddlepaddle-tiny是精简版paddle，减少依赖但也缺失某些优化，并且paddlepaddle-tiny不一定能同步更新

**Comment by TestNLP** [comment]
@Bond-H ，问题还是存在啊
######### run:list ##############
Traceback (most recent call last):
  File "lac/lac.py", line 234, in <module>
    result = lac.run(test_data)
  File "lac/lac.py", line 89, in run
    crf_decode = self.predictor.run([tensor_words])
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::memory::detail::MetadataCache::LoadDesc(paddle::memory::detail::MemoryBlock*)
2   paddle::memory::detail::BuddyAllocator::SplitToAlloc(std::__1::__tree_const_iterator<std::__1::tuple<unsigned long, unsigned long, void*>, std::__1::__tree_node<std::__1::tuple<unsigned long, unsigned long, void*>, void*>*, long>, unsigned long)
3   paddle::memory::detail::BuddyAllocator::Alloc(unsigned long)
4   void* paddle::memory::legacy::Alloc<paddle::platform::CPUPlace>(paddle::platform::CPUPlace const&, unsigned long)
5   paddle::memory::allocation::NaiveBestFitAllocator::AllocateImpl(unsigned long)
6   paddle::memory::allocation::AllocatorFacade::AllocShared(paddle::platform::Place const&, unsigned long)
7   paddle::memory::AllocShared(paddle::platform::Place const&, unsigned long)
8   paddle::framework::Tensor::mutable_data(paddle::platform::Place const&, paddle::framework::proto::VarType_Type, unsigned long)
9   paddle::operators::FusionGRUKernel<float>::SeqCompute(paddle::framework::ExecutionContext const&) const
10  paddle::operators::FusionGRUKernel<float>::Compute(paddle::framework::ExecutionContext const&) const
11  std::__1::__function::__func<paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::FusionGRUKernel<float>, paddle::operators::FusionGRUKernel<double> >::operator()(char const*, char const*, int) const::'lambda'(paddle::framework::ExecutionContext const&), std::__1::allocator<paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::FusionGRUKernel<float>, paddle::operators::FusionGRUKernel<double> >::operator()(char const*, char const*, int) const::'lambda'(paddle::framework::ExecutionContext const&)>, void (paddle::framework::ExecutionContext const&)>::operator()(paddle::framework::ExecutionContext const&)
12  paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
13  paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
14  paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
15  paddle::framework::NaiveExecutor::Run()
16  paddle::AnalysisPredictor::Run(std::__1::vector<paddle::PaddleTensor, std::__1::allocator<paddle::PaddleTensor> > const&, std::__1::vector<paddle::PaddleTensor, std::__1::allocator<paddle::PaddleTensor> >*, int)
17  void pybind11::cpp_function::initialize<paddle::pybind::(anonymous namespace)::BindAnalysisPredictor(pybind11::module*)::$_12, std::__1::vector<paddle::PaddleTensor, std::__1::allocator<paddle::PaddleTensor> >, paddle::AnalysisPredictor&, std::__1::vector<paddle::PaddleTensor, std::__1::allocator<paddle::PaddleTensor> > const&, pybind11::name, pybind11::is_method, pybind11::sibling>(paddle::pybind::(anonymous namespace)::BindAnalysisPredictor(pybind11::module*)::$_12&&, std::__1::vector<paddle::PaddleTensor, std::__1::allocator<paddle::PaddleTensor> > (*)(paddle::AnalysisPredictor&, std::__1::vector<paddle::PaddleTensor, std::__1::allocator<paddle::PaddleTensor> > const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::__invoke(pybind11::detail::function_call&)
18  pybind11::cpp_function::dispatcher(_object*, _object*, _object*)

----------------------
Error Message Summary:
----------------------
Error: Invalid CPU memory access
  [Hint: Expected desc->CheckGuards() == true, but received desc->CheckGuards():0 != true:1.] at (/home/teamcity/work/ef54dc8a5b211854/paddle/fluid/memory/detail/meta_cache.cc:35)
  [operator < fusion_gru > error]
libc++abi.dylib: terminating with uncaught exception of type paddle::platform::EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::memory::detail::MetadataCache::LoadDesc(paddle::memory::detail::MemoryBlock*)
2   paddle::memory::detail::BuddyAllocator::Free(void*)
3   void paddle::memory::legacy::Free<paddle::platform::CPUPlace>(paddle::platform::CPUPlace const&, void*, unsigned long)
4   paddle::memory::allocation::NaiveBestFitAllocator::FreeImpl(paddle::memory::allocation::Allocation*)
5   std::__1::__shared_ptr_pointer<paddle::memory::allocation::Allocation*, paddle::memory::allocation::Allocator::AllocationDeleter, std::__1::allocator<paddle::memory::allocation::Allocation> >::__on_zero_shared()
6   paddle::framework::Variable::PlaceholderImpl<paddle::framework::LoDTensor>::~PlaceholderImpl()
7   paddle::framework::Scope::~Scope()
8   paddle::framework::Scope::DeleteScope(paddle::framework::Scope*) const
9   paddle::AnalysisPredictor::~AnalysisPredictor()
10  paddle::AnalysisPredictor::~AnalysisPredictor()
11  pybind11::class_<paddle::AnalysisPredictor, paddle::PaddlePredictor>::dealloc(pybind11::detail::value_and_holder&)
12  pybind11::detail::clear_instance(_object*)
13  pybind11_object_dealloc

----------------------
Error Message Summary:
----------------------
Error: Invalid CPU memory access
  [Hint: Expected desc->CheckGuards() == true, but received desc->CheckGuards():0 != true:1.] at (/home/teamcity/work/ef54dc8a5b211854/paddle/fluid/memory/detail/meta_cache.cc:35)


Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

**Comment by TestNLP** [comment]
@Bond-H ，我跑的代码是你们的样例：lac.py
if __name__=="__main__":
    lac = LAC('lac_model')

    test_data = ['百度是一家高科技公司', 'LAC是一个优秀的分词工具', '']

    print('######### run:list ##############')
    result = lac.run(test_data)
    for res in result:
        print(' '.join(res))

    print('######### run:str ##############')
    result = lac.run(test_data[0])
    print(' '.join(result))

    print('######### run:tag ##############')
    result = lac.run(test_data, return_tag=True)
    for i, (sent, tags) in enumerate(result):
        result_list = ['(%s, %s)' % (ch, tag) for ch, tag in zip(sent, tags)]
        print(''.join(result_list))

    # 重训模型
    lac.train(model_save_dir='models_test',
              train_data='./data/train.tsv', test_data='./data/test.tsv')

    print('######### run:list ##############')
    result = lac.run(test_data)
    for res in result:
        print(' '.join(res))
    print('######### run:str ##############')
    result = lac.run(test_data[0])
    print(' '.join(result))
    print('######### run:tag ##############')
    result = lac.run(test_data, return_tag=True)
    for i, (sent, tags) in enumerate(result):
        result_list = ['(%s, %s)' % (ch, tag) for ch, tag in zip(sent, tags)]
        print(''.join(result_list))

**Comment by TestNLP** [comment]
@Bond-H ，我安装的依赖
Package              Version
-------------------- -------------------
absl-py              0.11.0
astor                0.8.1
certifi              2020.11.8
chardet              3.0.4
click                7.1.2
cycler               0.10.0
decorator            4.4.2
funcsigs             1.0.2
future               0.18.2
gast                 0.3.3
google-pasta         0.2.0
graphviz             0.15
grpcio               1.31.0
h5py                 2.10.0
idna                 2.10
importlib-metadata   1.7.0
joblib               0.17.0
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.0
kiwisolver           1.1.0
LAC                  2.0.5
Markdown             3.3.3
matplotlib           3.3.3
mkl-fft              1.2.0
mkl-random           1.1.1
mkl-service          2.3.0
nltk                 3.5
numpy                1.16.4
objgraph             3.5.0
opencv-python        4.2.0.32
paddlepaddle         1.8.5
pathlib              1.0.1
Pillow               8.0.1
pip                  20.2.4
prettytable          2.0.0
protobuf             3.14.0
pyparsing            2.4.7
python-dateutil      2.8.1
PyYAML               3.13
rarfile              4.0
regex                2020.11.13
requests             2.25.0
scipy                1.3.1
setuptools           50.3.1.post20201107
six                  1.15.0
tensorboard          1.14.0
tensorflow           1.14.0
tensorflow-estimator 1.14.0
termcolor            1.1.0
tornado              6.0.4
tqdm                 4.53.0
typed-ast            1.4.1
urllib3              1.26.2
wcwidth              0.2.5
Werkzeug             1.0.1
wheel                0.35.1
wrapt                1.12.1
zipp                 3.1.0

**Comment by Bond-H** [comment]
你仔细看看输入，是有空字串的……
BTW，lac.py中main其实是初期测试代码，部分接口已经修正过了，示例代码可以参考README

**Comment by KyleWang-Hunter** [comment]
> 你仔细看看输入，是有空字串的…… BTW，lac.py中main其实是初期测试代码，部分接口已经修正过了，示例代码可以参考README

你不是说的1.8.5版本已经修复了吗？人家传空字符串应该不会报错啊。
