### ISSUE TITLE
lac_demo 运行不了，提示W0808 10:51:53.736791 15022 init.cc:85] 'CUDA' is not supported, Please re-compile with WITH_GPU option

### ISSUE THREAD

**Issue by DearPolly** [baidu/lac#16]
~/git/Paddle/lac$ ./output/demo/lac_demo ./conf 20 8
Loaded q2b dic -- num = 172
Loaded strong punc -- num = 5
Loaded word dic -- num(with oov) = 20940
Loaded tag dic -- num = 57
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0808 10:51:53.736791 15022 init.cc:85] 'CUDA' is not supported, Please re-compile with WITH_GPU option
W0808 10:51:53.736852 15022 init.cc:101] 'CUDA' is not supported, Please re-compile with WITH_GPU option
Loaded customization dic -- num = 0
create lac handle successfully
create lac buff successfully
create lac buff successfully
create lac buff successfully
create lac buff successfully
create lac buff successfully
create lac buff successfully
create lac buff successfully
create lac buff successfully
然后就卡在这儿运行不下去了

安装的是 cuda-9.0 版本，不知道为什么不支持

**Comment by sdshq** [comment]
如果是按照文档来操作的，那么这些都是正常的log，因为文档里面编译Paddle的时候显式地关掉了GPU功能。之所以关掉GPU功能，是为了照顾大量没有N卡，或只有CPU的机器。
『卡住』的原因，是因为lac_demo在等待标准输入。
如果需要用GPU进行预测，需要向日志里面说的那样，编译一个带GPU支持的Paddle库。

**Comment by yuppx** [comment]
运行：./lac_demo /home/chase/yqs/Paddle/build/lac/conf 64 4
结果：Loaded q2b dic -- num = 172
Loaded strong punc -- num = 5
Loaded word dic -- num(with oov) = 20940
Loaded tag dic -- num = 57
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0814 14:05:31.713474 23358 init.cc:85] 'CUDA' is not supported, Please re-compile with WITH_GPU option
W0814 14:05:31.713518 23358 init.cc:101] 'CUDA' is not supported, Please re-compile with WITH_GPU option
Loaded customization dic -- num = 0
create lac handle successfully
create lac buff successfully
create lac buff successfully
create lac buff successfully
create lac buff successfully
西安、长沙、杭州、上海、深圳之后，南京也正式发文，对企业购房说不！昨日，南京市房产保障局官方微信“宜居南京”发布楼市新政：即日起，在全市范围内暂停向企事业单位及其他机构销售商品住房，2018年8月13日19：00后开始执行
出现了这样的错误：
Segmentation fault (core dumped)
请问有什么解决方法吗
