### ISSUE TITLE
如何去掉“Deprecated. Please use CreatePredictor instead.” 这个warning？

### ISSUE THREAD

**Issue by yayaQAQ** [baidu/lac#193]
调用lac的时候会报这个warning：
`/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(
W0508 10:57:49.234634 291947968 analysis_predictor.cc:1145] Deprecated. Please use CreatePredictor instead.`
使用是正常的，但是报这个warning就比较难受了。

**Comment by libertatis** [comment]
真的程序员是不会在意 Warning 的！除非是 Error~

**Comment by yayaQAQ** [comment]
但是它会在报错的时候重复打印两个log，就很难受了。

**Comment by junhua-huang** [comment]
> 

太真实了，笑死
