### ISSUE TITLE
lac是否不再支持gpu？

### ISSUE THREAD

**Issue by yayaQAQ** [baidu/lac#199]
想用cuda加速分词，但是发现分出来的结果不对。
input:`他是一名算法工程师。`
output:`{
    "msg": "",
    "results": [
        {
            "tag": [
                "a",
                "a",
"a",
                "a",
"a",
                "a",
                "a",
            ],
            "word": [
                "他",
                "是",
                "优秀",
                "的",
                "算法",
                "工程师",
                "。"
            ]
        }
    ],
    "status": "000"
}`
tag的结果全是“a”，比较离谱。

**Comment by nikohpng** [comment]
我也是同样的问题，得到的结果也全是a

**Comment by yayaQAQ** [comment]
应该不会去支持cuda了，就这样吧。
