### ISSUE TITLE
lac 2.1.2，能改进公司名的分词吗？谢谢！公司名的分词和标注相当的弱，

### ISSUE THREAD

**Issue by rocke2020** [baidu/lac#211]
赢创(上海)投资管理有限公司
[['赢创', '(', '上海', ')', '投资', '管理', '有限公司'], ['v', 'w', 'LOC', 'w', 'vn', 'vn', 'ORG']]

'奥冉（上海）建设工程设计有限公司'
[['奥冉', '（', '上海', '）', '建设工程设计', '有限公司'], ['PER', 'w', 'LOC', 'w', 'ORG', 'ORG']]

这种很明显的公司名称，分词错误率太高了。
能增加公司名称的训练数据吗？谢谢！！

**Comment by nicolasmeng** [comment]
感觉比老版本要弱了

**Comment by rocke2020** [comment]
能改进公司名称的效果吗？谢谢！！
目前公司名称效果，真太差太差，根本不能使用。
诺-n 戴-v 商务-n 咨询-vn (上海)-ORG 有限公司-ORG
