### ISSUE TITLE
c++使用 rank_model 运行 lac_demo 和 lac_multi 时 core dump

### ISSUE THREAD

**Issue by kevinzsy** [baidu/lac#216]
操作系统：CentOS 7.9
paddle c++ 预测库版本：manylinux_cpu_avx_mkl_gcc8.2 (manylinux_cpu_avx_openblas_gcc8.2 也试过结果一样)
LAC 版本：2.1.0

lac_model 和 seg_model 均可正常运行。
rank_model 运行时 core dump，报错如下：

$ output/bin/lac_demo models_general/rank_model/
---    fused 0 scale with matmul
---    Fused 0 MatmulTransposeReshape patterns
我爱北京
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/mnt/huangdingbang/anaconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/mnt/huangdingbang/anaconda3/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/mnt/huangdingbang/anaconda3/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 1875, in embedding
    'padding_idx': padding_idx
  File "/mnt/huangdingbang/zhouchengjie/keyword/net.py", line 34, in lstm_net
    ne_emb = fluid.layers.embedding(input=ne_feature, size=[ne_dict_dim, ne_emb_dim], dtype='float32')
  File "main.py", line 124, in create_model
    result, avg_cost, acc = net.lstm_net(args, words, ne_features, mode, target=labels)
  File "main.py", line 341, in train
    args, mode=mode)
  File "main.py", line 490, in <module>
    train(args, 'train')

----------------------
Error Message Summary:
----------------------
Error: ShapeError: The last dimensions of the 'Ids' tensor must be 1. But received Ids's last dimensions = 0, Ids's shape = [0].
  [Hint: Expected ids_dims[ids_rank - 1] == 1, but received ids_dims[ids_rank - 1]:0 != 1:1.] at (/paddle/paddle/fluid/operators/lookup_table_op.cc:51)
  [operator < lookup_table > error]
Aborted (core dumped)

请问是否我的环境配置有问题？谢谢

**Comment by zmingshi** [comment]
麻烦问下，这个是c++ 版本不支持吗？还是其他原因呢~
