### ISSUE TITLE
python如何支持多进程？

### ISSUE THREAD

**Issue by kenwestern** [baidu/lac#251]
如题，每次只能单进程运行，一开多进程就提示lac文件正在使用，就挂掉

**Comment by kenwestern** [comment]
支持多进程的，原来问题的关键是一次批量处理的条数不能太大，一个进程下一次不要超过1000条，已解决

**Comment by logan0czy** [comment]
> 支持多进程的，原来问题的关键是一次批量处理的条数不能太大，一个进程下一次不要超过1000条，已解决

您好，麻烦问一下这个lac多进程是怎么实现的呢，需要在每一个进程里面新增实例吗
