### ISSUE TITLE
编译lac出错

### ISSUE THREAD

**Issue by 352174109** [baidu/lac#26]
报错信息
Scanning dependencies of target lac
[ 12%] Building CXX object CMakeFiles/lac.dir/src/lac_util.cpp.o
[ 25%] Building CXX object CMakeFiles/lac.dir/src/ilac.cpp.o
In file included from /paddle/build/lac/src/lac.h:17:0,
                 from /paddle/build/lac/src/ilac.cpp:16:
/paddle/build/lac/src/main_tagger.h:21:40: fatal error: paddle/fluid/platform/init.h: No such file or directory
compilation terminated.
CMakeFiles/lac.dir/build.make:86: recipe for target 'CMakeFiles/lac.dir/src/ilac.cpp.o' failed
make[2]: *** [CMakeFiles/lac.dir/src/ilac.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/lac.dir/all' failed
make[1]: *** [CMakeFiles/lac.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by yangperasd** [comment]
使用v0.15.0可以解决这个错误。
注意不要使用v0.15.0以上的版本，以上的版本API变化（fluid.io中移除了get_inference_program）。

**Comment by zhuchenxi** [comment]
> 使用v0.15.0可以解决这个错误。
> 注意不要使用v0.15.0以上的版本，以上的版本API变化（fluid.io中移除了get_inference_program）。

请问这里v0.15.0指的是paddle还是lac的版本呢？paddle有指定0.14的版本，lac没看到有版本的选择？

**Comment by jshower** [comment]
在paddle v0.15.0以上的版本，paddle中目前删除掉了paddle/fluid/platform/init.h这个头文件，你可以通过在代码中删除这个头文件的方式，或者依赖lac的for_paddle_v1.1分支来解决这个问题。

**Comment by zigennlp** [comment]
在Paddle项目中，我使用 git checkout v0.15.0 后，

$ make -j 4 

仍然出现这类错误：

`[  4%] Built target extern_glog
paddle/fluid/platform/CMakeFiles/profiler_py_proto.dir/build.make:60: *** target pattern contains no '%'.  Stop.
CMakeFiles/Makefile2:1895: recipe for target 'paddle/fluid/platform/CMakeFiles/profiler_py_proto.dir/all' failed
make[1]: *** [paddle/fluid/platform/CMakeFiles/profiler_py_proto.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....


`

**Comment by zigennlp** [comment]
如果我不是用 make -j 4 ， 而是直接使用 make

出现这样的错误：

> cpp/Paddle/paddle/fluid/string/tinyformat/tinyformat.h: In function ‘const char* paddle::string::tinyformat::detail::streamStateFromFormat(std::ostream&, bool&, int&, const char*, const paddle::string::tinyformat::detail::FormatArg*, int&, int)’:

cpp/Paddle/paddle/fluid/string/tinyformat/tinyformat.h:673:15: error: this statement may fall through [-Werror=implicit-fallthrough=]
       out.setf(std::ios::uppercase);
       ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~


> cc1plus: all warnings being treated as errors
paddle/fluid/platform/dynload/CMakeFiles/dynamic_loader.dir/build.make:62: recipe for target 'paddle/fluid/platform/dynload/CMakeFiles/dynamic_loader.dir/dynamic_loader.cc.o' failed
make[2]: *** [paddle/fluid/platform/dynload/CMakeFiles/dynamic_loader.dir/dynamic_loader.cc.o] Error 1
CMakeFiles/Makefile2:2234: recipe for target 'paddle/fluid/platform/dynload/CMakeFiles/dynamic_loader.dir/all' failed
make[1]: *** [paddle/fluid/platform/dynload/CMakeFiles/dynamic_loader.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zigennlp** [comment]
@yangperasd 

我把 warning 去掉后，可以编译了， 有碰到如下错误：

>[ 14%] Built target profiler_py_proto_init
>paddle/fluid/platform/CMakeFiles/profiler_py_proto.dir/build.make:60: *** target pattern contains no '%'.  Stop.
>CMakeFiles/Makefile2:1811: recipe for target 'paddle/fluid/platform/CMakeFiles/profiler_py_proto.dir/all' failed
>make[1]: *** [paddle/fluid/platform/CMakeFiles/profiler_py_proto.dir/all] Error 2
>Makefile:151: recipe for target 'all' failed
>make: *** [all] Error 2


这类错误我是比较头疼的，因为并没有提示源代码那里错误。

多半，是环境问题。

目前我的环境是：
Ubuntu 18.x
g++,cmake,protoc的版本也都符合要求。

源代码路径也都是英文的，没有空格。

>build$ ls -lth paddle/fluid/platform/CMakeFiles/profiler_py_proto.dir
>total 16K
>-rw-r--r-- 1 john john   21 1月  30 19:56 progress.make
>-rw-r--r-- 1 john john  236 1月  30 19:56 cmake_clean.cmake
>-rw-r--r-- 1 john john 3.8K 1月  27 18:03 build.make
>-rw-r--r-- 1 john john  316 1月  27 18:03 DependInfo.cmake

**Comment by zigennlp** [comment]
接上条，里面有提到：CMakeFiles/Makefile2 文件 1811 行出错了， 我把 1811 的行找到了：


>#=============================================================================
># Target rules for target paddle/fluid/platform/CMakeFiles/profiler_py_proto.dir
>
># All Build rule for target.
>paddle/fluid/platform/CMakeFiles/profiler_py_proto.dir/all: paddle/fluid/platform/CMakeFiles/profiler_py_proto_init.dir/all
>        $(MAKE) -f paddle/fluid/platform/CMakeFiles/profiler_py_proto.dir/build.make paddle/fluid/platform/CMakeFiles/profiler_py_proto.dir/depend  ( **### 这是第1811行** )
>        $(MAKE) -f paddle/fluid/platform/CMakeFiles/profiler_py_proto.dir/build.make paddle/fluid/platform/CMakeFiles/profiler_py_proto.dir/build
>        @$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --progress-dir=/opt/usr/sourcecode/cpp/Paddle/build/CMakeFiles --progress-num= "Built target profiler_py_proto"
>.PHONY : paddle/fluid/platform/CMakeFiles/profiler_py_proto.dir/all

**Comment by yangperasd** [comment]
把gcc的报错信息给出来会更好的定位错误，只给makefile的信息几乎是没有用的

**Comment by zigennlp** [comment]
@yangperasd   的确如此。 

我现在已经编译通过了。

原因还是不熟悉paddlepaddle编译过程。 犯了基本的错误。

再次感谢

**Comment by zhuchenxi** [comment]
@yangperasd 最后找到原因了，应该是有些机器不支持高级指令集，需要编译的时候加上-DWITH_AVX=OFF解决问题

**Comment by ChuanTianML** [comment]
> 使用v0.15.0可以解决这个错误。
> 注意不要使用v0.15.0以上的版本，以上的版本API变化（fluid.io中移除了get_inference_program）。

尝试用该方案解决，遇到新的问题，在安装python包时：
λ c7e90c696896 /paddle {(v0.15.0)} pip install build/python/dist/*.whl
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Double requirement given: paddlepaddle==0.14.0 from file:///paddle/build/python/dist/paddlepaddle-0.14.0-cp27-cp27mu-linux_x86_64.whl (already in paddlepaddle==0.0.0 from file:///paddle/build/python/dist/paddlepaddle-0.0.0-cp27-cp27mu-linux_x86_64.whl, name='paddlepaddle')

**Comment by ChuanTianML** [comment]
> 使用v0.15.0可以解决这个错误。
> 注意不要使用v0.15.0以上的版本，以上的版本API变化（fluid.io中移除了get_inference_program）。

解决了我的问题，感谢。

**Comment by 352174109** [comment]
多谢多谢

**Comment by Super-Storm** [comment]
我使用使用lac仓库的for_paddle_v1.1分支重新编译解决了该问题
