### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [baidu/lac#3]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [lac_destroy](https://github.com/baidu/lac/blob/18d7131a57a404d7890d7be61527ef7671c8e287/src/ilac.cpp#L31 "lac_destroy function")
- [MainTagger](https://github.com/baidu/lac/blob/18d7131a57a404d7890d7be61527ef7671c8e287/src/main_tagger.cpp#L30 "Destructor for MainTagger")

**Comment by sdshq** [comment]
Thanks for the feedback. Will do:)

**Comment by elfring** [comment]
Would it be nicer to keep this issue open until it will be really fixed?

**Comment by sdshq** [comment]
Sorry for that. I will push the fix today.
