### ISSUE TITLE
请问lac整体安装有不用docker的离线解决方案么？

### ISSUE THREAD

**Issue by zhuchenxi** [baidu/lac#36]
目前现在需要安装的机器上，不支持docker，也不支持网络。
但似乎在make的过程中需要大量git clone xxx
有办法可以在没有docker也没有网络的机器上成功安装lac么？

**Comment by jshower** [comment]
没有网络会导致很多依赖库无法下载。能否在类似配置的有网络的机器上编译好后，将可执行文件和模型复制到需要安装的机器上？

**Comment by zhuchenxi** [comment]
> 没有网络会导致很多依赖库无法下载。能否在类似配置的有网络的机器上编译好后，将可执行文件和模型复制到需要安装的机器上？

@jshower 请问这里类似配置需要要求哪些是一致的？仅操作系统版本一致（比如ubuntu 16.04）就可以保证编译后的可以迁移么？
