### ISSUE TITLE
/bin/ld: cannot find -lmkldnn when make lac

### ISSUE THREAD

**Issue by Charliechen1** [baidu/lac#4]
Hi,

I have encounter an error:
`/bin/ld: cannot find -lmkldnn`
when I try to make the lac project
but I have already installed mkldnn with pip and the lib file `libmkldnn.so.0` exist in the /usr/lib directory. What the reason for this phenomena, what should I do to complete the installation?

Thank you.

**Comment by sdshq** [comment]
The cmakelist file has the logic to automatically probe mkldnn in PADDLE_ROOT. It may have some glitch, feel free to modify it.

**Comment by sdshq** [comment]
If compiled following README.md, mkldnn is not supposed to be enabled. We disabled mkldnn by default because the mkldnn lib that comes with Paddle is not working properly. Please inform us if a stand-alone version of mkldnn works, especially when Paddle is not compiled with it.

**Comment by 540369718** [comment]
我也遇到这个问题了。
要把libmkldnn.so.0的路径加入LIBRARY_PATH才行
