### ISSUE TITLE
python infer.py怎么应用自定义词典customization.dic

### ISSUE THREAD

**Issue by hss7** [baidu/lac#40]
如题，根据示例配置了customization.dic， 但是调用python  infer.py，但是没有起到预期的效果(与词的边界无关)。 需要在哪边设置入参么

**Comment by jshower** [comment]
customization.dic目前只在C++版的预测代码中进行了使用，在python版的预测代码中没有写对应的对齐逻辑。

**Comment by hss7** [comment]
好的，了解了...
