### ISSUE TITLE
可以增量训练吗？

### ISSUE THREAD

**Issue by xidianfushuai** [baidu/lac#41]
你好：
        lac开源模型对于一般语句的识别效果已经很好了，但对特定领域的识别效果不太好，所以我想基于开源的模型增量训练。如果想增量训练，需要用save_persistables接口保存模型，而lac用的是save_inference_model接口，没法直接增量训练。所以想问一下，有什么办法可以增量训练吗？

**Comment by jshower** [comment]
其实save_persistables里面保存的变量在save_inference_model中也都已经保存了，如果你想要增量训练，只需要将那些变量在增量训练前重新load起来，代替默认重新初始化的变量就可以了。具体的实现你可以直接参考paddle本身对模型保存与重训的代码，并不复杂。
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/io.py

**Comment by xidianfushuai** [comment]
好的，我试试，非常感谢哈
