### ISSUE TITLE
源码是不是有内存泄漏

### ISSUE THREAD

**Issue by young2010** [baidu/lac#43]
源码是不是有内存泄漏
void lac_buff_destroy(void* lac_handle, void* lac_buff) {
    if (lac_handle == NULL && lac_buff != NULL) {
        ((Lac*) lac_handle)->destroy_buff(lac_buff);
    }
}

**Comment by hitwangshuai** [comment]
对呀，感觉是不是有内存泄漏，代码有bug？应该是：lac_handle != NULL吧

**Comment by sunhf** [comment]
多谢提醒，这里应该改成lac_handle != NULL。

**Comment by hitwangshuai** [comment]
> 多谢提醒，这里应该改成lac_handle != NULL。

好像依然还有内存泄漏，多线程下调用压测内存泄漏比较严重

**Comment by young2010** [comment]
> 多谢提醒，这里应该改成lac_handle != NULL。

只是改判断还是有问题, _main_tagger->destroy_buff(buff);没干活直接return了

void Lac::destroy_buff(void* buff) const
{
    if (buff != NULL) {
        if (_main_tagger != NULL) {
            _main_tagger->destroy_buff(buff);
        }

**Comment by young2010** [comment]
> > 多谢提醒，这里应该改成lac_handle != NULL。
> 
> 好像依然还有内存泄漏，多线程下调用压测内存泄漏比较严重

是的，只要destory就会有问题，如果只加载一次模型可以放在主线程里
