### ISSUE TITLE
lac的make时出错，显示fatal error：xxhash.h cannot find

### ISSUE THREAD

**Issue by qingmei-migu** [baidu/lac#44]
前面的一切安装正常，但是在lac的make时，提示xxhash.h找不到；
我搜索了一下，fluid的build路径下面是有xxhash.h，而且报的错误是paddle本身代码的问题

用的是paddle v1.4版本；lac是for_paddle_1.1；

In file included from /home/lac/src/lac_glb.h:22:0,
                 from /home/lac/src/customization_tagger.h:20,
                 from /home/lac/src/customization_tagger.cpp:15:
/home/Paddle-release-1.4/build/fluid_install_dir/paddle/fluid/framework/scope.h:
18:20: fatal error: xxhash.h: No such file or directory
 #include <xxhash.h>
                    ^
compilation terminated.
make[2]: *** [CMakeFiles/lac.dir/src/customization_tagger.cpp.o] Error 1
make[1]: *** [CMakeFiles/lac.dir/all] Error 2
make: *** [all] Error 2

**Comment by symsimmy** [comment]
> 前面的一切安装正常，但是在lac的make时，提示xxhash.h找不到；
> 我搜索了一下，fluid的build路径下面是有xxhash.h，而且报的错误是paddle本身代码的问题
> 
> 用的是paddle v1.4版本；lac是for_paddle_1.1；
> 
> In file included from /home/lac/src/lac_glb.h:22:0,
> from /home/lac/src/customization_tagger.h:20,
> from /home/lac/src/customization_tagger.cpp:15:
> /home/Paddle-release-1.4/build/fluid_install_dir/paddle/fluid/framework/scope.h:
> 18:20: fatal error: xxhash.h: No such file or directory
> #include <xxhash.h>
> ^
> compilation terminated.
> make[2]: *** [CMakeFiles/lac.dir/src/customization_tagger.cpp.o] Error 1
> make[1]: *** [CMakeFiles/lac.dir/all] Error 2
> make: *** [all] Error 2

我也一样

**Comment by qingmei-migu** [comment]
> > 前面的一切安装正常，但是在lac的make时，提示xxhash.h找不到；
> > 我搜索了一下，fluid的build路径下面是有xxhash.h，而且报的错误是paddle本身代码的问题
> > 用的是paddle v1.4版本；lac是for_paddle_1.1；
> > In file included from /home/lac/src/lac_glb.h:22:0,
> > from /home/lac/src/customization_tagger.h:20,
> > from /home/lac/src/customization_tagger.cpp:15:
> > /home/Paddle-release-1.4/build/fluid_install_dir/paddle/fluid/framework/scope.h:
> > 18:20: fatal error: xxhash.h: No such file or directory
> > #include <xxhash.h>
> > ^
> > compilation terminated.
> > make[2]: *** [CMakeFiles/lac.dir/src/customization_tagger.cpp.o] Error 1
> > make[1]: *** [CMakeFiles/lac.dir/all] Error 2
> > make: *** [all] Error 2
> 
> 我也一样

lac用1.1版本，paddle也换成1.1版本，我安装正常了~

**Comment by jtyoui** [comment]
![image](https://user-images.githubusercontent.com/28988355/58318299-0f3f5800-7e4a-11e9-8703-e77e47ea5c4d.png)

**Comment by jtyoui** [comment]
> /home/Paddle-release-1.4/build/fluid_install_dir/paddle/fluid/framework/scope.h

/home/Paddle-release-1.4/build/fluid_install_dir/paddle/fluid/framework/scope.h 里面改成
 extern "C" {
#include "xxhash.h"
}
就可以了。或者把xxhash.h移到相对路径。

**Comment by jtyoui** [comment]
> > > 前面的一切安装正常，但是在lac的make时，提示xxhash.h找不到；
> > > 我搜索了一下，fluid的build路径下面是有xxhash.h，而且报的错误是paddle本身代码的问题
> > > 用的是paddle v1.4版本；lac是for_paddle_1.1；
> > > In file included from /home/lac/src/lac_glb.h:22:0,
> > > from /home/lac/src/customization_tagger.h:20,
> > > from /home/lac/src/customization_tagger.cpp:15:
> > > /home/Paddle-release-1.4/build/fluid_install_dir/paddle/fluid/framework/scope.h:
> > > 18:20: fatal error: xxhash.h: No such file or directory
> > > #include <xxhash.h>
> > > ^
> > > compilation terminated.
> > > make[2]: *** [CMakeFiles/lac.dir/src/customization_tagger.cpp.o] Error 1
> > > make[1]: *** [CMakeFiles/lac.dir/all] Error 2
> > > make: *** [all] Error 2
> > 
> > 
> > 我也一样
> 
> lac用1.1版本，paddle也换成1.1版本，我安装正常了~

/home/Paddle-release-1.4/build/fluid_install_dir/paddle/fluid/framework/scope.h 里面改成
extern "C" {
#include "xxhash.h"
}
就可以了。或者把xxhash.h移到相对路径。

**Comment by jtyoui** [comment]
#include "paddle/fluid/framework/fleet/fleet_wrapper.h"
这个文件找不到？
/home/baidu/Paddle/build/fluid_install_dir/paddle/fluid/framework/data_feed.h:29:56: fatal error: paddle/fluid/framework/fleet/fleet_wrapper.h: No such file or directory
 #include "paddle/fluid/framework/fleet/fleet_wrapper.h"
compilation terminated.
make[2]: *** [CMakeFiles/lac.dir/src/customization_tagger.cpp.o] Error 1
make[1]: *** [CMakeFiles/lac.dir/all] Error 2
make: *** [all] Error 2
