### ISSUE TITLE
目标模式不含有“%”

### ISSUE THREAD

**Issue by jtyoui** [baidu/lac#45]
[  8%] Built target profiler_py_proto_init
paddle/fluid/platform/CMakeFiles/profiler_py_proto.dir/build.make:60: *** 目标模式不含有“%”。 停止。
make[1]: *** [paddle/fluid/platform/CMakeFiles/profiler_py_proto.dir/all] 错误 2
make: *** [all] 错误 2

**Comment by fenglc** [comment]
`sudo apt install protobuf-compiler`

**Comment by fenglc** [comment]
`sudo apt install protobuf-compiler`

**Comment by fenglc** [comment]
#26
