### ISSUE TITLE
请问这个项目和PaddleNLP/lexical_analysis是不是同一个项目？

### ISSUE THREAD

**Issue by logicgogh** [baidu/lac#46]
如题，请问这两个项目是等价的吗？可以直接使用PaddleNLP代替这个吗？

**Comment by Halfish** [comment]
是同一个，PaddleNLP/lexical_analysis 是从 baidu/lac 这个项目迁移过去的，不过目前暂时没有迁移 C++ 版本。

**Comment by Bond-H** [comment]
两者定位不同，baidu/lac偏向于应用，用户可便捷快速的调用我们提供的模型，目前baidu/lac的库已经升级，极大的提升用户使用的便利性，支持pip安装和c++、java等多语言调用。
而PaddleNLP/lexical_analysis 则偏向于学术模型调研使用，可能需要一定的门槛，使用该库可进行模型训练与调研，同时该库训练所得的模型经过简易转换也可使用baidu/lac的调用接口直接调用
