### ISSUE TITLE
你好，您们的语料库是公开的吗，哪里可以下载，谢谢

### ISSUE THREAD

**Issue by CuiZhiyuan12138** [baidu/lac#54]
你好，您们的语料库是公开的吗，哪里可以下载，谢谢

**Comment by Bond-H** [comment]
我们的语料暂未公开，不过我们整理了一些[公开的语料](https://xumingzhi9.github.io/github-nlp-progress/#词法分析)，对该方向该兴趣的同学可以自行下载和测试：对于开源的分词数据集lac提供了简易的训练接口；而对于词性标注和实体识别数据集，目前还需进行标签映射后方可使用。

**Comment by CuiZhiyuan12138** [comment]
谢谢大佬
