### ISSUE TITLE
如何提速

### ISSUE THREAD

**Issue by lmxhappy** [baidu/lac#55]
用lac做ner的时候，发现速度不是那么理想。有什么办法，可以提速呢？这个很重要，当query条目太多的时候，特别耗时。

**Comment by Bond-H** [comment]
以批量的形式输入，性能会有所提升，这点在README中有所介绍
如果有GPU条件的情况下，可以使用GPU + **批量输入**的形式进一步提升性能，需预先安装[paddle-gpu版](https://www.paddlepaddle.org.cn/install/quick)

启动时开启GPU选项
```python
from LAC import LAC
lac = LAC(use_cuda=False)
```

> 注：GPU的形式需要**批量输入**才能发挥其并行计算的优势，一般设置batch_size为50+
