### ISSUE TITLE
seg模式和lac模式输出了不一样的分词结果

### ISSUE THREAD

**Issue by Vergissmeinicht** [baidu/lac#57]
我用"朝着坏了的灯泡舞着别离"作为LAC(mode='seg')和LAC(mode='lac'的)输入，分别输出了一下两个结果：
['朝着', '坏', '了', '的', '灯泡', '舞', '着', '别离']
[['朝着', '坏', '了', '的', '灯泡舞', '着', '别离'], ['p', 'a', 'u', 'u', 'n', 'u', 'vn']]
出现了不一样的分词结果，这是正常的吗？那应该以哪个为准？

**Comment by Bond-H** [comment]
嗯嗯，是的，因为考虑到性能以及分词训练等需求的原因，我们'seg'和'lac'的mode目前是两个独立的模型，两者结果会有细微的diff，但差距很小，根据自己需求进行选择即可，如果只用分词，选择'seg'，有着显著性能优势；如果还需要用到标注结果，则推荐直接使用'lac'，分别获取分词和标注结果
