### ISSUE TITLE
关于字典问题

### ISSUE THREAD

**Issue by HappyLynn** [baidu/lac#58]
发现models那个词法分析与这个项目的字典不一致，这个更小，比如“原”这个字都没有，感觉这个字很常见啊？不知道优化词表有没有什么根据？

**Comment by Bond-H** [comment]
嗯嗯，是的，LAC2.0有对字表进行优化，合并了繁体字，异形字以及对个别字符进行了归一化处理，能够更好的兼容繁体和生僻字语料问题，归一化词典可参见`q2b.dic`，“原”这个字在`q2b.dic`词典中，信息不会丢失
