### ISSUE TITLE
文件没有关闭

### ISSUE THREAD

**Issue by zhangzhenhu** [baidu/lac#59]
https://github.com/baidu/lac/blob/49416fc738daa3d3e131b130242f2ab6eb84fb68/python/LAC/reader.py#L34

**Comment by lishoujun** [comment]
> file is a path-like object giving the pathname (absolute or relative to the current working directory) of the file to be opened or an integer file descriptor of the file to be wrapped. (If a file descriptor is given, it is closed when the returned I/O object is closed, unless closefd is set to False.)

[docs of io.open() ](https://docs.python.org/3/library/functions.html#open
)

**Comment by Bond-H** [comment]
fixed
