### ISSUE TITLE
fail to run lac_demo

### ISSUE THREAD

**Issue by Charliechen1** [baidu/lac#6]
Hi, 
I have executed the demo file as `./output/demo/lac_demo conf 200 1`.
But I got the following error messages:

> Loaded q2b dic -- num = 172
Loaded strong punc -- num = 5
Loaded word dic -- num(with oov) = 20940
Loaded tag dic -- num = 57
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  Fail to parse program_desc from binary string. at [/home/craiditx/Paddle/paddle/fluid/framework/program_desc.cc:88]
PaddlePaddle Call Stacks: 
0             0x4184d3p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 355
1       0x7f2001f29827p paddle::framework::ProgramDesc::ProgramDesc(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 823
2       0x7f2001eca13fp paddle::inference::Load(paddle::framework::Executor*, paddle::framework::Scope*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 287
3             0x415606p lac::MainTagger::init_model(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 262
4             0x4160b2p lac::MainTagger::create(char const*) + 530
5             0x40c3d1p lac::Lac::create(char const*) + 945
6             0x40951bp lac_create + 11
7             0x40899bp init_dict(char const*) + 11
8             0x409191p test_main(int, char**) + 97
9             0x408769p main + 9
10      0x7f2000e7b830p __libc_start_main + 240
11            0x4088b9p _start + 41

Would you please give me some advice to solve that? Thank you!

**Comment by jshower** [comment]
Please make sure that all the files in the repository have been downloaded completely, because the files of our model are large, so they are stored with Git LFS. Please check whether the files in the conf directory are completely downloaded.

**Comment by sdshq** [comment]
Are you running the project in docker environment?

**Comment by Charliechen1** [comment]
no, but ubuntu 16.04

**Comment by sdshq** [comment]
Please list the files under the `conf' dir in your environment. Let's verify the integrity of the conf first, and please allow us taking some time to construct a system like yours and try to replicate the problem.

**Comment by wanbiguizhao** [comment]
do  command `git lfs pull` in  path_code_dir

**Comment by kev123456** [comment]
I met similar problem.
Loaded q2b dic -- num = 172
Loaded strong punc -- num = 5
Loaded word dic -- num(with oov) = 20940
Loaded tag dic -- num = 57
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  out of memory at [/data/kev/nlp/paddle/Paddle/paddle/fluid/platform/device_context.cc:150]
PaddlePaddle Call Stacks: 
0             0x417294p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 628
1       0x7f12a7c05b76p paddle::platform::CUDADeviceContext::CUDADeviceContext(paddle::platform::CUDAPlace) + 3222
2       0x7f12a7c06478p paddle::platform::DeviceContextPool::DeviceContextPool(std::vector<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::allocator<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > const&) + 552
3       0x7f12a7c0b83ap paddle::framework::InitDevices(bool, std::vector<int, std::allocator<int> >) + 602
4       0x7f12a7c0ba59p paddle::framework::InitDevices(bool) + 281
5             0x41439bp lac::MainTagger::init_model(std::string const&) + 27
6             0x41476ap lac::MainTagger::create(char const*) + 410
7             0x40ab49p lac::Lac::create(char const*) + 505
8             0x40801bp lac_create + 11
9             0x40758bp init_dict(char const*) + 11
10            0x407d02p test_main(int, char**) + 82
11            0x407369p main + 9
12      0x7f129ccce445p __libc_start_main + 245
13            0x4074b7p

Aborted

**Comment by GitWhilebear** [comment]
you can download the files listed in the /conf ( include the files in the /conf/model) one by one from the web page.
