### ISSUE TITLE
    predictor::Clone是否线程安全？

### ISSUE THREAD

**Issue by FrankWork** [baidu/lac#63]
我看多线程的程序中用了  _predictor(lac._predictor->Clone()), 请问这个操作是线程安全的吗？

https://github.com/PaddlePaddle/Paddle/issues/24887

**Comment by FrankWork** [comment]
我本地测试时，将1个句子复制多份，多线程会跑出多种结果。单线程只跑出1种结果。

**Comment by Bond-H** [comment]
> 我看多线程的程序中用了 _predictor(lac._predictor->Clone()), 请问这个操作是线程安全的吗？
> 
> [PaddlePaddle/Paddle#24887](https://github.com/PaddlePaddle/Paddle/issues/24887)

我们这边的实现在测试时并未发现线程安全的问题，不过我们会进一步去确认，因为涉及到paddle内部的实现。


> 我本地测试时，将1个句子复制多份，多线程会跑出多种结果。单线程只跑出1种结果。

你使用的输入是什么呢，我简单测了一下，并没有复现该问题

**Comment by FrankWork** [comment]
./lac_multi models_general/seg_model/ 10 < input > out

输入是这句话，复制64遍
6月9日消息，近日，湖人名宿沙奎尔-奥尼尔在参加NFL球队圣徒队的视频会议时以自己和科比-布莱恩特为例表示，如果不是当年被媒体分裂，OK组合本可以夺得8个总冠军。

**Comment by FrankWork** [comment]
./lac_multi models_general/seg_model/ 8 < input > out

**Comment by FrankWork** [comment]
![image](https://user-images.githubusercontent.com/13351333/84129835-0df0c580-aa75-11ea-93c0-e21ba01980bf.png)

**Comment by Bond-H** [comment]
我们这边测试输出都是正常且与单线程一致的，并不存在多线程结果不一致的问题，从你的结果截图上看，应该是在打印时，线程加锁出现问题导致的，存在多个线程同时打印，这个可能与相应的环境有关，因为demo中的输出打印只是我们给的一个示例，如非我们的模型导致的问题的话，需要用户自行排查

**Comment by Bond-H** [comment]
Clone函数的实现内部有加锁，我们这个实现是线程安全的。

**Comment by FrankWork** [comment]
原因是g_mutex没初始化，在mac下有问题

`pthread_mutex_init(&g_mutex, NULL);`

**Comment by Bond-H** [comment]
原来如此，感谢提醒！
