### ISSUE TITLE
支持加载多个自定义词典

### ISSUE THREAD

**Issue by luozhouyang** [baidu/lac#71]
根据加载自定义词典的代码实现[load_customization](https://github.com/baidu/lac/blob/69286a9e51d7eec0dcbf38064e41f3668ac88b81/python/LAC/custom.py#L42)，目前只支持加载一个自定义词典。

但是很多情况下用户可能整理出了多个词典，手动合成一个虽然可行，但是略显麻烦。加载自定义词典这里是否可以改成支持多个文件呢？

例如：

```python
from LAC import LAC
lac = LAC()

# 装载干预词典
lac.load_customization(['custom_a.txt', 'custom_b.txt'])

# 干预后结果
custom_result = lac.run(u"春天的花开秋天的风以及冬天的落阳")
```

**Comment by Bond-H** [comment]
嗯嗯，感谢您的建议，我们会酌情考虑的。
