### ISSUE TITLE
装载链接库

### ISSUE THREAD

**Issue by Liaid** [baidu/lac#72]
LacDemo示例文件中：
执行System.loadLibrary("lacjni"); 一直提示 no lacjni in java.library.path。
请问装载链接库的目录是怎么生成的？
注：预测库是下载的编译好的预测库。

**Comment by Bond-H** [comment]
> 注：预测库是下载的编译好的预测库。

目前Java调用还相对麻烦，需要进行编译生成链接库，预测库的准备只是第1步，还需参考 [2-jni编译生成java调用包](https://github.com/baidu/lac/tree/master/java#2-jni编译生成java调用包)完成编译，参照文档完成编译后会在`output/java`目录下生成运行调用的目录，具体操作可参照Java调用的README文档：https://github.com/baidu/lac/tree/master/java

感谢您的反馈，因为考虑到兼容性等问题，目前Java调用还不是那么便捷，后续我们会进一步进行优化

**Comment by Liaid** [comment]
2-jni编译生成java调用包，这一步已经完成，但是没有生成output目录，期间也没有报错，请问怎么解决？。output/java和java这两个目录有什么区别，不能直接运行java的demo吗

**Comment by Bond-H** [comment]
是如果执行了`make install`命名的话，会构造生成output目录的。output/java目录和java目录会去除c++代码并增加编译好的动态库文件，你可以直接编译好的动态库`liblacjni.so`放入java的目录下运行LacDemo，或者修改LacDemo中`System.setProperty("java.library.path", ".");`，指定`liblacjni.so`所在的路径https://github.com/baidu/lac/blob/69286a9e51d7eec0dcbf38064e41f3668ac88b81/java/LacDemo.java#L11

**Comment by Liaid** [comment]
![image](https://user-images.githubusercontent.com/61965382/85982937-3ab34f80-ba19-11ea-9322-056f9defc7cc.png)
在build文件夹加下执行make install，提示make: *** No rule to make target 'install'.  Stop.

**Comment by Bond-H** [comment]
> 2-jni编译生成java调用包，这一步已经完成，但是没有生成output目录，期间也没有报错

在build目录执行`make install`之前需要运行cmake的命令的，你在`jni编译`这一步运行是参照[README文档](https://github.com/baidu/lac/tree/master/java#2-jni%E7%BC%96%E8%AF%91%E7%94%9F%E6%88%90java%E8%B0%83%E7%94%A8%E5%8C%85)中的脚本运行的吗？此处脚本已经有运行`make install`了，

**Comment by Liaid** [comment]
![img](https://user-images.githubusercontent.com/61965382/85985989-1ad25a80-ba1e-11ea-929d-4927ac21f90b.png)
make install之前已经运行了cmake命令，这是cmake命令在build目录生成的文件，是否有问题？

**Comment by Bond-H** [comment]
哦哦，从你这文件上看，应该是Windows系统，且cmake应该是使用Visual Studio，使用Visual Studio打开lac.sln项目文件，运行编译，产出lacjni.dll文件放到java目录下运行即可

**Comment by Liaid** [comment]
![img](https://user-images.githubusercontent.com/61965382/86095182-25efbe00-bae4-11ea-81d3-dc0c69d3409b.png)
vs运行编译lac.sln失败

**Comment by elihuan1990** [comment]
> ![img](https://user-images.githubusercontent.com/61965382/86095182-25efbe00-bae4-11ea-81d3-dc0c69d3409b.png)
> vs运行编译lac.sln失败，是否还有其他解决方案

我也遇到这种情况了，你解决了嘛？我感觉他们的步骤好乱呀，windows和linux下的情况也不分别说明。

**Comment by machengc** [comment]
还没有解决

**Comment by machengc** [comment]
> > ![img](https://user-images.githubusercontent.com/61965382/86095182-25efbe00-bae4-11ea-81d3-dc0c69d3409b.png)
> > vs运行编译lac.sln失败，是否还有其他解决方案
> 
> 我也遇到这种情况了，你解决了嘛？我感觉他们的步骤好乱呀，windows和linux下的情况也不分别说明。

还没有解决

**Comment by Liaid** [comment]
> > ![img](https://user-images.githubusercontent.com/61965382/86095182-25efbe00-bae4-11ea-81d3-dc0c69d3409b.png)
> > vs运行编译lac.sln失败，是否还有其他解决方案
> 
> 我也遇到这种情况了，你解决了嘛？我感觉他们的步骤好乱呀，windows和linux下的情况也不分别说明。

还没有解决

**Comment by Bond-H** [comment]
抱歉因为此前对Windows编译相关描述的不足给大家带来一定的困扰，目前我们已更新兼容Windows的CMake文件，补全了相关文档，并在[release](https://github.com/baidu/lac/releases)提供了一个基于mkldnn的编译好的java文件`lac4javawin.zip`，对编译过程感兴趣的同学可以参考https://github.com/baidu/lac/blob/master/compile4windows.md 进行编译

**Comment by zhou1323** [comment]
> 抱歉因为此前对Windows编译相关描述的不足给大家带来一定的困扰，目前我们已更新兼容Windows的CMake文件，补全了相关文档，并在[release](https://github.com/baidu/lac/releases)提供了一个基于mkldnn的编译好的java文件`lac4javawin.zip`，对编译过程感兴趣的同学可以参考https://github.com/baidu/lac/blob/master/compile4windows.md 进行编译

你好，请问下载了‘lac4javawin.zip’之后要如何使用呢？
按照[README](https://github.com/baidu/lac/tree/master/java)所说的，我在第一步依赖库准备部分于Paddle官网下载了已经编译好的Windows预测库，第二步jni编译部分下载了lac4javawin.zip，第三步运行LacDemo测试的时候报错:
`Exception in thread "main" java.lang.UnsatisfiedLinkError: no lacjni in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at LacDemo.<clinit>(LacDemo.java:12)`
修改12行的代码，改用System.load加载绝对路径的文件时报错:
`Exception in thread "main" java.lang.UnsatisfiedLinkError: E:\Test\lac\lac4javawin\lacjni.dll: Can't find dependent libraries
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at LacDemo.<clinit>(LacDemo.java:14)`

**Comment by Bond-H** [comment]
是paddle的依赖库未找到，可在lac4javawin.zip 解压目录中直接执行LacDemo
