### ISSUE TITLE
jni编译，生成java调用包，运行脚本报错

### ISSUE THREAD

**Issue by yeyuelong** [baidu/lac#73]
![jni](https://user-images.githubusercontent.com/20420441/85976658-924bbe00-ba0d-11ea-9365-47033f6cc6ee.jpg)
![jni_build](https://user-images.githubusercontent.com/20420441/85976662-94ae1800-ba0d-11ea-9556-982e17919aa2.jpg)

在执行脚本的时候报错：
CMake Error: The source directory "/opt/lac" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** 没有规则可以创建目标“install”。 停止。

请问是什么原因呢？

**Comment by Bond-H** [comment]
git clone lac之后需要先`cd lac`，进入到lac目录中再后续编译操作，此处是我们疏忽了，感谢反馈

**Comment by yeyuelong** [comment]
嗯，可以了，谢谢！
