### ISSUE TITLE
关于效果的一点咨询

### ISSUE THREAD

**Issue by HITlilingzhi** [baidu/lac#8]
请问有和现有的一些语义分析工具做效果上的对比实验吗？

**Comment by sdshq** [comment]
LAC利用DNN拟合了百度AI开放平台上的词法分析服务，达到了优于后者的分析效果，效果对比请参见[我们的技术报告](https://arxiv.org/abs/1807.01882)。
而根据百度AI开放平台上线时的评估结论，开放平台上的词法分析服务是优于主要的几大现有产品的。

**Comment by hellomotor** [comment]
薄熙来到重庆考察

lac分词结果:
薄熙 PER 0 6    来到 v 6 6      重庆 LOC 12 6   考察 v 18 6

百度AI平台NLP接口:
薄熙来/n 到/v 重庆/n 考察/v

**Comment by sdshq** [comment]
感谢反馈！lac是一个纯粹的字序列标注模型，没有引入任何实体资源。因此在个别歧义case上可能不如带有丰富实体资源的百度AI平台版本。在使用堆叠GRU网络拟合带有大量外部资源的复杂策略这个问题上，我们做了很多努力，让一个37M的模型基本上复现了G级别模型的效果，在新闻文本的总体效果甚至要优于后者。
具体到这个case，lac把重庆识别为LOC，这点要强于AI平台，但是句首的人名切分错误不可接受，因此整个case整体上是badcase。这和统计学习的特性有关，高频的东西比较容易记住，相对低频的东西还是需要资源的辅助，尤其是在模型体量极小的情况下。

**Comment by sdshq** [comment]
后续我们会想办法把资源编码到网络当中，在效果和模型体量上达到一个更好的平衡。
