### ISSUE TITLE
java版本问题

### ISSUE THREAD

**Issue by zhouzusheng** [baidu/lac#80]
java 版本又两个问题，与设计有关
第一个问题 LAC 加载的模型貌似没法删除。 当 LAC 对象被回收后， jni 分配的内存 如何释放
第二个问题 LAC 貌似不是线程安全的， 如果每个线程 new 一个LAC 是否开销过大？ 对于不是线程池模式启动线程使用LAC，
new LAC 更加会由于问题1 而崩溃

**Comment by zhouzusheng** [comment]
我修改了一下

 public BaiduLac(BaiduLac model) {
        from(model.self_ptr);
    }

    @Override
    protected void finalize() throws Throwable {
        close();
        super.finalize();
    }

    public void close() {
        if(self_ptr != 0) {
            clear(self_ptr);
            self_ptr = 0;
        }
    }

 private native void from(long self_ptr);
 private static native void clear(long self_ptr);

其中 两个 native 实现方法只有两三行代码， 就不贴了。

**Comment by Bond-H** [comment]
感谢反馈！JAVA调用程序确实有所疏忽

**Comment by Bond-H** [comment]
该问题已修复
