### ISSUE TITLE
lac和tf pip包版本问题

### ISSUE THREAD

**Issue by DachuanZhao** [baidu/lac#81]
```
ERROR: tensorflow 2.2.0 has requirement scipy==1.4.1; python_version >= "3", but you'll have scipy 1.3.1 which is incompatible.
```
lac没有用1.4.1版本，而是用的1.3.1，是否能升级到1.4.1和tf保持一致呢？

**Comment by Bond-H** [comment]
lac对于1.4.1和1.3.1都是兼容的，可以忽略这个提示，或者通过命令`pip install lac scipy==1.4.1`的形式安装scipy 1.4.1

**Comment by DachuanZhao** [comment]
> lac对于1.4.1和1.3.1都是兼容的，可以忽略这个提示，或者通过命令`pip install lac scipy==1.4.1`的形式安装scipy 1.4.1

是的，我试了一下没有问题，就是 pip装的时候会降级，可以考虑下次发布的时候升级一下pip文件哈~
