### ISSUE TITLE
make 最后10%时，出错提示下面的信息。

### ISSUE THREAD

**Issue by elihuan1990** [baidu/lac#82]
[  9%] Building CXX object CMakeFiles/lac.dir/c++/src/ahocorasick.cpp.obj
[ 18%] Building CXX object CMakeFiles/lac.dir/c++/src/lac.cpp.obj
[ 27%] Building CXX object CMakeFiles/lac.dir/c++/src/lac_custom.cpp.obj
[ 36%] Building CXX object CMakeFiles/lac.dir/c++/src/lac_util.cpp.obj
[ 45%] Linking CXX static library liblac.a
[ 45%] Built target lac
Scanning dependencies of target lacjni
[ 54%] Building CXX object CMakeFiles/lacjni.dir/c++/src/ahocorasick.cpp.obj
[ 63%] Building CXX object CMakeFiles/lacjni.dir/c++/src/lac.cpp.obj
[ 72%] Building CXX object CMakeFiles/lacjni.dir/c++/src/lac_custom.cpp.obj
[ 81%] Building CXX object CMakeFiles/lacjni.dir/c++/src/lac_util.cpp.obj
[ 90%] Building CXX object CMakeFiles/lacjni.dir/java/cpp/lac_jni.cpp.obj
D:\58nlp\Lac2.0\lac\java\cpp\lac_jni.cpp: In function 'void _set_self(JNIEnv*, jobject, LAC*)':
D:\58nlp\Lac2.0\lac\java\cpp\lac_jni.cpp:28:22: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   28 |     jlong selfPtr = *(jlong *)&self;
      |                      ^~~~~~~~~~~~~~
D:\58nlp\Lac2.0\lac\java\cpp\lac_jni.cpp: In function 'LAC* _get_self(JNIEnv*, jobject)':
D:\58nlp\Lac2.0\lac\java\cpp\lac_jni.cpp:36:13: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   36 |     return *(LAC **)&selfPtr;
      |             ^~~~~~~~~~~~~~~~
make[2]: *** No rule to make target 'mkldnn-NOTFOUND', needed by 'liblacjni.dll'.  Stop.
CMakeFiles\Makefile2:122: recipe for target 'CMakeFiles/lacjni.dir/all' failed
make[1]: *** [CMakeFiles/lacjni.dir/all] Error 2
Makefile:147: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by elihuan1990** [comment]
java调用，cmake时用了 -G "MinGW Makefiles"用了mingwmake兼容的makefile，然后成功的cmake了
cmake -G "MinGW Makefiles" -DPADDLE_ROOT=$PADDLE_ROOT -DJAVA_HOME=$JAVA_HOME -DWITH_JNILIB=ON -DWITH_DEMO=OFF ../
-- The CXX compiler identification is GNU 9.2.0
-- The C compiler identification is GNU 9.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/MinGW/bin/g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/MinGW/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- CXX compiler: C:/MinGW/bin/g++.exe, version: GNU 9.2.0
-- C compiler: C:/MinGW/bin/gcc.exe, version: GNU 9.2.0
-- paddle include: D:/58nlp/Lac2.0/fluid_inference_install_dir/paddle/include
-- paddle lib: D:/58nlp/Lac2.0/fluid_inference_install_dir/paddle/lib
-- MKLDNN lib found.
-- MKLML lib found.
-- 'D:/58nlp/Lac2.0/lac' output dir
-- Configuring done
-- Generating done
-- Build files have been written to: D:/58nlp/Lac2.0/lac/build
但是，在makefile的时候，提示make[2]: *** No rule to make target 'mkldnn-NOTFOUND', needed by 'liblacjni.dll'. Stop.错误！我用的windows版编译好的paddle，难道需要下源码，在用mingwmake兼容的模式编译一遍paddle源码嘛？

**Comment by zhouzusheng** [comment]
windows 编译好的，java 要用，应该用VS + cmake吧？用 MinGW可以吗

**Comment by zhouzusheng** [comment]
解决了吗？ 我用的是没有
GPU 版本， openblas ， 没遇到你的问题。

**Comment by elihuan1990** [comment]
> 解决了吗？ 我用的是没有
> GPU 版本， openblas ， 没遇到你的问题。

我准备下paddle的源码，用mingw编译一遍
