### ISSUE TITLE
自定义词典加载不支持带有空格的词

### ISSUE THREAD

**Issue by HuanLiuNLP** [baidu/lac#83]
load customization字典的时候，
words = line.strip().split()，对于有空格的自定义词会错误分开，如iphone 12，the shy等。
对于一行多个自定义词的情况，是否换一个分隔符更合适?

**Comment by Bond-H** [comment]
已该问题已修复，通过命令`pip install lac --upgrade` 更新LAC至2.0.4版本

load_customization函数增加sep的参数用于设置分隔符，默认为None时，以空格或制表符'\t'进行切分，可根据需要切换为其他字符，如仅使用'\t':
```Python
lac.load_customization('custom.txt', sep='\t')
```

**Comment by HuanLiuNLP** [comment]
nice
