### ISSUE TITLE
mkldnn-NOTFOUND

### ISSUE THREAD

**Issue by elihuan1990** [baidu/lac#88]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误		'mkldnn-NOTFOUND', needed by 'lacjni.dll', missing and no known rule to make it	D:\58nlp\Lac2.0\lac\out\build\x64-Debug\lac	D:\58nlp\Lac2.0\lac\out\build\x64-Debug\ninja	1

**Comment by elihuan1990** [comment]
已为配置“x64-Debug”启动 CMake 生成。
1> 命令行: "cmd.exe" /c ""c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\cmake\CMake\bin\cmake.exe"  -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH="D:\58nlp\Lac2.0\lac\out\install\x64-Debug" -DWITH_JNILIB:BOOL="True" -DWITH_DEMO:BOOL="False" -DCMAKE_CXX_FLAGS:STRING="/DWIN32 /D_WINDOWS /W3 /GR /EHsc" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/HostX64/x64/cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/HostX64/x64/cl.exe"  -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_MAKE_PROGRAM="c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\cmake\Ninja\ninja.exe" "D:\58nlp\Lac2.0\lac" 2>&1"
1> 工作目录: D:\58nlp\Lac2.0\lac\out\build\x64-Debug
1> [CMake] -- CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/HostX64/x64/cl.exe, version: MSVC 19.26.28806.0
1> [CMake] -- C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/HostX64/x64/cl.exe, version: MSVC 19.26.28806.0
1> [CMake] -- paddle include: D:/58nlp/Lac2.0/cpumkl/fluid_inference_install_dir/paddle/include
1> [CMake] -- paddle lib: D:/58nlp/Lac2.0/cpumkl/fluid_inference_install_dir/paddle/lib
1> [CMake] -- MKLDNN lib found.
1> [CMake] -- MKLML lib found.
1> [CMake] -- 'D:/58nlp/Lac2.0/lac' output dir
1> [CMake] -- Configuring done
1> [CMake] -- Generating done
1> [CMake] -- Build files have been written to: D:/58nlp/Lac2.0/lac/out/build/x64-Debug
1> 已提取 CMake 变量。
1> 已提取源文件和标头。
1> 已提取代码模型。
1> 已提取包含路径。
1> CMake 生成完毕。
cmake的时候，已经提示MKLDNN lib found，MKLML lib found，为什么lacjni.dll会提示需要mkldnn-NOTFOUND需要呢？显然它是没有找到mkldnn的库。

**Comment by zhouzusheng** [comment]
你可以去看我的版本 https://github.com/zhouzusheng/lac

**Comment by Bond-H** [comment]
此前的CMakeList.txt文件未能兼顾到Windows的系统，目前已完成兼容更新，并在release提供了一个基于mkldnn的编译好的java文件lac4javawin.zip，若希望自行编译可参考文档 https://github.com/baidu/lac/blob/master/compile4windows.md
