### ISSUE TITLE
运行lac_demo，Segmentation fault

### ISSUE THREAD

**Issue by zhyon404** [baidu/lac#91]
按照c++编译教程，下载了ubuntu14.04_cpu_avx_openblas。编译后运行出现Segmentation fault
![image](https://user-images.githubusercontent.com/32242529/86999426-27586f00-c1e5-11ea-9d2d-5f3a3e1b10c3.png)
gdb截图
![image](https://user-images.githubusercontent.com/32242529/86999513-5838a400-c1e5-11ea-9ce3-9f79822d9e9b.png)
![image](https://user-images.githubusercontent.com/32242529/86999548-65559300-c1e5-11ea-8916-33de4eaf305c.png)

**Comment by zhouzusheng** [comment]
我linux 版也是。 只需要自己编译paddle 预测库就可以。 真正的原因是你编译器 的stl 版本与百度编译时不兼容。自己编译一遍就没事。

**Comment by zhyon404** [comment]
使用hub.baidubce.com/paddlepaddle/paddle:latest-dev 运行成功了，gcc版本 4.8
hub.baidubce.com/paddlepaddle/paddle:latest编译不成功，gcc版本5.x。

尝试了4.9。也不行。

考虑提paddle供多版本的gcc的编译库？
