### ISSUE TITLE
Python版LAC处理大文本内存占用过大

### ISSUE THREAD

**Issue by gary02** [baidu/lac#94]
同样的500w字数文本, paddlehub版本的lac可以3分钟内处理完， 而lac会短时间内占满内存导致处理失败（或被oom kill， 或Segmentation fault）

paddlehub 内存占用：
![plot-hub](https://user-images.githubusercontent.com/13580441/87298193-5f8ce400-c53c-11ea-83ea-e18627132c56.png)
lac 内存占用:
![plot-lac](https://user-images.githubusercontent.com/13580441/87298212-66b3f200-c53c-11ea-8be0-be152d5969cb.png)

### 环境参数
- Python 3.6.11
- Linux ubuntu 4.18.10-041810-generic 
- Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
- 16g 内存

### 测试代码
```python
import paddlehub as hub
from LAC import LAC


def re_seg(texts, target):
    resegged_texts = ['']
    for text in texts:
        if len(resegged_texts[-1]) < target:
            resegged_texts[-1] += text
        else:
            resegged_texts.append(text)
    else:
        return resegged_texts


def hub_seg_worgtags(text):
    lac = hub.Module(name="lac")
    results = lac.lexical_analysis(data={'text': re_seg(text.splitlines(), 30000)})
    for result in results:
        for w, t in zip(result['word'], result['tag']):
            yield w, '' if '\n' in w else t


def lac_seg_wordtags(text):
    lac = LAC()
    # lac.load_customization('lac-custom.txt', sep=None)
    texts = re_seg(text.splitlines(), 30000)
    return [list(zip(*i)) for i in lac.run(texts)]


with open('从零开始-500w.txt') as fp:
    text=fp.read()

# print(lac_seg_wordtags(text))
print(list(hub_seg_worgtags(text)))
```

### 测试文本
[从零开始-500w.txt](https://github.com/baidu/lac/files/4912050/-500w.txt)

**Comment by Bond-H** [comment]
模型无法同时处理这么多数据的，都是要分批，正常batch大小不用超过200，因为再大无性能提升且占用内存，只是paddlehub原本的接口做了额外的封装

**Comment by gary02** [comment]
> 模型无法同时处理这么多数据的，都是要分批，正常batch大小不用超过200，因为再大无性能提升且占用内存，只是paddlehub原本的接口做了额外的封装

确实, 代码改成分批执行即可处理完：
```python
def lac_seg_wordtags(text):
    lac = LAC()
    # lac.load_customization('lac-custom.txt', sep=None)
    texts = re_seg(text.splitlines(), 30000)
    return [list(zip(*lac.run(s))) for s in texts]
```
谢谢！
