### ISSUE TITLE
load_customization方法应能接受数据结构或fileobject

### ISSUE THREAD

**Issue by gary02** [baidu/lac#97]
load_customization 目前只接受文件路径作为参数，不能传fileobject， 在比如从oss或者内存里加载自定义词典的情景里，需要额外的硬盘IO去调用接口。

**Comment by gary02** [comment]
或者提供一个更底层的可以接受fileobject或数据结构的接口

**Comment by Bond-H** [comment]
嗯嗯，这个我们会考虑的，customization的代码我们安排下周进行优化升级，升级后至少Python调用是能满足这种需求的

**Comment by DachuanZhao** [comment]
> 嗯嗯，这个我们会考虑的，customization的代码我们安排下周进行优化升级，升级后至少Python调用是能满足这种需求的

请问现在升级好了嘛？期待ing

**Comment by jieli4970** [comment]
自定义词典，词生效，但是词性没生效，请问有遇到这个情况吗？用的提供的lac demo测试

**Comment by gary02** [comment]
2.1.0 增加了add_word 方法， 关闭issue
